ExamenMusicaNetCoreMVC/Models/Albume.cs
using System;
using System.Collections.Generic;

namespace ExamenMusicaNetCoreMVC.Models;

public partial class Albume
{
    public int Id { get; set; }

    public DateOnly? Fecha { get; set; }

    public string? Genero { get; set; }

    public string? Titulo { get; set; }

    public int? GruposId { get; set; }

    public virtual ICollection<Cancione> Canciones { get; set; } = new List<Cancione>();

    public virtual Grupo? Grupos { get; set; }
}

ExamenMusicaNetCoreMVC/Controllers/AlbumesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

using ExamenMusicaNetCoreMVC.Models;
using ExamenMusicaNetCoreMVC.Servicios.RepositorioGenerico;

namespace ExamenMusicaNetCoreMVC.Controllers
{
    public class AlbumesController : Controller
    {
        private readonly IRepositorioGenerico<Albume> _context;
        private readonly IRepositorioGenerico<VistaAlbume> _contextVista;
        private readonly IRepositorioGenerico<Grupo> _grupoContext;

        public AlbumesController(IRepositorioGenerico<Albume> context, IRepositorioGenerico<Grupo> grupoContext, IRepositorioGenerico<VistaAlbume> contextVista)
        {
            _context = context;
            _grupoContext = grupoContext;
            _contextVista = contextVista;

        }

        // GET: Albumes
        public async Task<IActionResult> Index()
        {

            var examenMusicaNetCoreMVCContext = await _contextVista.DameTodos();

            return View(examenMusicaNetCoreMVCContext);
        }

        public async Task<IActionResult> IndexAlbum()
        {

            var examenMusicaNetCoreMVCContext = await _contextVista.DameTodos();
            var filtrado = from album in examenMusicaNetCoreMVCContext
                where album.Genero.ToLower().Equals("heavy metal") && album.Titulo.Contains("u")
                select album;


            return View(filtrado);
        }

        // GET: Albumes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var albume = await _contextVista.DameUno((int)id);
            if (albume == null)
            {
                return NotFound();
            }

            return View(albume);
        }

        // GET: Albumes/Create
        public async Task<IActionResult> Create()
        {
            ViewData["GruposId"] = new SelectList(await _grupoContext.DameTodos(), "Id", "Nombre");
            return View();
        }

        // POST: Albumes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Fecha,Genero,Titulo,GruposId")] Albume albume)
        {
            if (ModelState.IsValid)
            {
                await _context.Agregar((Albume)albume);;
                return RedirectToAction(nameof(Index));
            }
            ViewData["GruposId"] = new SelectList(await _grupoContext.DameTodos(), "Id", "Nombre", albume.GruposId);
            return View(albume);
        }

        // GET: Albumes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var albume = await _context.DameUno((int)id);
            if (albume == null)
            {
                return NotFound();
            }
            ViewData["GruposId"] = new SelectList(await _grupoContext.DameTodos(), "Id", "Nombre", albume.GruposId);
            return View(albume);
        }

        // POST: Albumes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Fecha,Genero,Titulo,GruposId")] Albume albume)
        {
            if (id != albume.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                     _context.Modificar(id, albume);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AlbumeExists(albume.Id).Result)
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["GruposId"] = new SelectList(await _grupoContext.DameTodos(), "Id", "Nombre", albume.GruposId);
            return View(albume);
        }

        // GET: Albumes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var albume = await _context.DameUno((int)id);
            if (albume == null)
            {
                return NotFound();
            }

            return View(albume);
        }

        // POST: Albumes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var albume = _context.DameUno((int)id);
            if (albume != null)
            {
                await _context.Borrar((int)id);
            }

            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> AlbumeExists(int id)
        {
            var datos = await _context.DameTodos();
            return datos.Any(e => e.Id == id);

        }
    }
}

ExamenMusicaNetCoreMVC/Views/Albumes/Create.cshtml
@model ExamenMusicaNetCoreMVC.Models.Albume

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Albumes</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Fecha" class="control-label"></label>
                <input asp-for="Fecha" class="form-control" />
                <span asp-validation-for="Fecha" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genero" class="control-label"></label>
                <input asp-for="Genero" class="form-control" />
                <span asp-validation-for="Genero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GruposId" class="control-label"></label>
                <select asp-for="GruposId" class="form-control" asp-items="ViewBag.GruposId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ExamenMusicaNetCoreMVC/Views/Albumes/Delete.cshtml
@model ExamenMusicaNetCoreMVC.Models.Albume

@{
    ViewData["Title"] = "Delete";
}

<h1>Deletes</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Albume</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fecha)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genero)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genero)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GruposId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GruposId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ExamenMusicaNetCoreMVC/Views/Albumes/Details.cshtml
@model ExamenMusicaNetCoreMVC.Models.VistaAlbume

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Albumes</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fecha)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genero)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genero)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreGrupo) del Grupo
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreGrupo)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ExamenMusicaNetCoreMVC/Views/Albumes/Edit.cshtml
@model ExamenMusicaNetCoreMVC.Models.Albume

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Albumes</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Fecha" class="control-label"></label>
                <input asp-for="Fecha" class="form-control" />
                <span asp-validation-for="Fecha" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genero" class="control-label"></label>
                <input asp-for="Genero" class="form-control" />
                <span asp-validation-for="Genero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GruposId" class="control-label"></label>
                <select asp-for="GruposId" class="form-control" asp-items="ViewBag.GruposId"></select>
                <span asp-validation-for="GruposId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ExamenMusicaNetCoreMVC/Views/Albumes/Index.cshtml
@model IEnumerable<ExamenMusicaNetCoreMVC.Models.VistaAlbume>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<a asp-action="index" asp-controller="Albumes" class="p-3">Index</a><a asp-action="indexAlbum" asp-controller="Albumes" class="p-3">IndexFiltro</a>
<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Busca por titulo: <input id="texto" type="text" name="SearchString" value="@ViewData["CurrentFilter"]" />
            <input type="submit" value="Search" class="btn btn-default" /> |
            <a asp-action="Index">Vuelve a la lista entera</a>
        </p>
    </div>
</form>
<table class="table" id="tableData">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Fecha)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genero)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Titulo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NombreGrupo) del Grupo
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Fecha)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genero)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Titulo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NombreGrupo)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
    <ul class="pagination pagination-lg pager" id="myPager"></ul>
</table>

ExamenMusicaNetCoreMVC/Views/Albumes/IndexAlbum.cshtml
@model IEnumerable<ExamenMusicaNetCoreMVC.Models.VistaAlbume>

@{
    ViewData["Title"] = "AlbumFiltrado";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<a asp-action="index" asp-controller="Albumes" class="p-3">Index</a><a asp-action="indexAlbum" asp-controller="Albumes" class="p-3">IndexFiltro</a>
<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Busca por titulo: <input id="texto" type="text" name="SearchString" value="@ViewData["CurrentFilter"]" />
            <input type="submit" value="Search" class="btn btn-default" /> |
            <a asp-action="Index">Vuelve a la lista entera</a>
        </p>
    </div>
</form>
<table class="table" id="tableData">
    <thead>
        <tr>
            <th>
                <@* a asp-action="Index" asp-route-sortOrder="@ViewData["OrdenFechaNO"]"> *@@Html.DisplayNameFor(model => model.Fecha)@* </a>*@
            </th>
            <th>
                @* <a asp-action="Index" asp-route-sortOrder="@ViewData["OrdenGeneroNO"]"> *@@Html.DisplayNameFor(model => model.Genero)@* </a>*@
            </th>
            <th>
                @* <a asp-action="Index" asp-route-sortOrder="@ViewData["OrdenTituloNO"]"> *@@Html.DisplayNameFor(model => model.Titulo)@* </a>*@
            </th>
            <th>
                @* <a asp-action="Index" asp-route-sortOrder="@ViewData["OrdenGrupoNO"]"> *@@Html.DisplayNameFor(model => model.NombreGrupo) del Grupo@* </a>*@
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Fecha)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Genero)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Titulo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NombreGrupo)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
    <ul class="pagination pagination-lg pager" id="myPager"></ul>
</table>