ExamenMusicaNetCoreMVC/Controllers/ConciertoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ExamenMusicaNetCoreMVC.Models;
using ExamenMusicaNetCoreMVC.Servicios.RepositorioGenerico;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExamenMusicaNetCoreMVC.Controllers
{
    public class ConciertoesController : Controller
    {
        private readonly IRepositorioGenerico<Concierto> _context;

        public ConciertoesController(IRepositorioGenerico<Concierto> context)
        {
            _context = context;
        }

        // GET: Conciertoes
        public async Task<IActionResult> Index(string sortOrder, string searchString)
        {
            return View(await _context.DameTodos());
        }

        public async Task<IActionResult> IndexConcierto()
        {
            var conciertos = await _context.DameTodos();
            var filtrado = from concierto in conciertos
                where concierto.Precio > 30 && ((DateTime)concierto.Fecha).Year > 2015
                select concierto;

            return View(filtrado);
        }

        // GET: Conciertoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var concierto = await _context.DameUno((int)id);
            if (concierto == null)
            {
                return NotFound();
            }

            return View(concierto);
        }

        // GET: Conciertoes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Conciertoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Fecha,Genero,Lugar,Titulo,Precio")] Concierto concierto)
        {
            if (ModelState.IsValid)
            {
                await _context.Agregar(concierto);
                return RedirectToAction(nameof(Index));
            }
            return View(concierto);
        }

        // GET: Conciertoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var concierto = await _context.DameUno((int)id);
            if (concierto == null)
            {
                return NotFound();
            }
            return View(concierto);
        }

        // POST: Conciertoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Fecha,Genero,Lugar,Titulo,Precio")] Concierto concierto)
        {
            if (id != concierto.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Modificar((int)id, concierto);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!(await ConciertoExists(concierto.Id)))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(concierto);
        }

        // GET: Conciertoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var concierto = await _context.DameUno((int)id);
            if (concierto == null)
            {
                return NotFound();
            }

            return View(concierto);
        }

        // POST: Conciertoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var concierto = _context.DameUno((int)id);
            if (concierto != null)
            {
                await _context.Borrar((int)id);
            }

            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> ConciertoExists(int id)
        {
            var datos = await _context.DameTodos();
             return datos.Any(e => e.Id == id);
        }
    }
}

ExamenMusicaNetCoreMVC/Views/Conciertoes/Create.cshtml
@model ExamenMusicaNetCoreMVC.Models.Concierto

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Conciertos</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Fecha" class="control-label"></label>
                <input asp-for="Fecha" class="form-control" />
                <span asp-validation-for="Fecha" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genero" class="control-label"></label>
                <input asp-for="Genero" class="form-control" />
                <span asp-validation-for="Genero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Lugar" class="control-label"></label>
                <input asp-for="Lugar" class="form-control" />
                <span asp-validation-for="Lugar" class="text-danger"></span>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                    <input asp-for="Precio" class="form-control" type="number" step=".01" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ExamenMusicaNetCoreMVC/Views/Conciertoes/Delete.cshtml
@model ExamenMusicaNetCoreMVC.Models.Concierto

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Conciertos</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fecha)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genero)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genero)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Lugar)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Lugar)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ExamenMusicaNetCoreMVC/Views/Conciertoes/Details.cshtml
@model ExamenMusicaNetCoreMVC.Models.Concierto

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Conciertos</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fecha)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genero)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genero)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Lugar)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Lugar)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ExamenMusicaNetCoreMVC/Views/Conciertoes/Edit.cshtml
@model ExamenMusicaNetCoreMVC.Models.Concierto

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Conciertos</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Fecha" class="control-label"></label>
                <input asp-for="Fecha" class="form-control" />
                <span asp-validation-for="Fecha" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genero" class="control-label"></label>
                <input asp-for="Genero" class="form-control" />
                <span asp-validation-for="Genero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Lugar" class="control-label"></label>
                <input asp-for="Lugar" class="form-control" />
                <span asp-validation-for="Lugar" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ExamenMusicaNetCoreMVC/Views/Conciertoes/Index.cshtml
@model IEnumerable<ExamenMusicaNetCoreMVC.Models.Concierto>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<a asp-action="index" asp-controller="Conciertoes" class="p-3">Index</a><a asp-action="indexConcierto" asp-controller="Conciertoes" class="p-3">IndexFiltro</a>
<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Busca por Genero: <input id="texto"  type="text" name="SearchString" value="@ViewData["CurrentFilter"]" />
            <input type="submit" value="Search" class="btn btn-default" /> |
            <a asp-action="Index">Vuelve a la lista entera</a>
        </p>
    </div>
</form>
<table class="table" id="tableData">
    <thead>
        <tr>
            <th>
                @* <a asp-action="Index" asp-route-sortOrder="@ViewData["OrdenFechaNO"]"> *@@Html.DisplayNameFor(model => model.Fecha)@*</a>*@
            </th>
            <th>
                @* <a asp-action="Index" asp-route-sortOrder="@ViewData["OrdenGeneroNO"]"> *@@Html.DisplayNameFor(model => model.Genero)@*</a>*@
            </th>
            <th>
                @* <a asp-action="Index" asp-route-sortOrder="@ViewData["OrdenLugarNO"]"> *@@Html.DisplayNameFor(model => model.Lugar)@*</a>*@
            </th>
            <th>
                @* <a asp-action="Index" asp-route-sortOrder="@ViewData["OrdenTituloNO"]"> *@@Html.DisplayNameFor(model => model.Titulo)@*</a>*@
            </th>
            <th>
                @* <a asp-action="Index" asp-route-sortOrder="@ViewData["OrdenPrecioNO"]"> *@@Html.DisplayNameFor(model => model.Precio)@*</a>*@
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Fecha)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genero)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Lugar)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Titulo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Precio)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
    <ul class="pagination pagination-lg pager" id="myPager"></ul>
</table>

ExamenMusicaNetCoreMVC/Views/Conciertoes/IndexConcierto.cshtml
@model IEnumerable<ExamenMusicaNetCoreMVC.Models.Concierto>

@{
    ViewData["Title"] = "IndexConcierto";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<a asp-action="index" asp-controller="Conciertoes" class="p-3">Index</a><a asp-action="indexConcierto" asp-controller="Conciertoes" class="p-3">IndexFiltro</a>
<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Busca por Genero: <input id="texto" type="text" name="SearchString" value="@ViewData["CurrentFilter"]" />
            <input type="submit" value="Search" class="btn btn-default" /> |
            <a asp-action="Index">Vuelve a la lista entera</a>
        </p>
    </div>
</form>
<table class="table" id="tableData">
    <thead>
        <tr>
            <th>
                @* <a asp-action="Index" asp-route-sortOrder="@ViewData["OrdenFechaNO"]"> *@@Html.DisplayNameFor(model => model.Fecha)@*</a>*@
            </th>
            <th>
                @* <a asp-action="Index" asp-route-sortOrder="@ViewData["OrdenGeneroNO"]"> *@@Html.DisplayNameFor(model => model.Genero)@*</a>*@
            </th>
            <th>
                @* <a asp-action="Index" asp-route-sortOrder="@ViewData["OrdenLugarNO"]"> *@@Html.DisplayNameFor(model => model.Lugar)@*</a>*@
            </th>
            <th>
                @* <a asp-action="Index" asp-route-sortOrder="@ViewData["OrdenTituloNO"]"> *@@Html.DisplayNameFor(model => model.Titulo)@*</a>*@
            </th>
            <th>
                @* <a asp-action="Index" asp-route-sortOrder="@ViewData["OrdenPrecioNO"]"> *@@Html.DisplayNameFor(model => model.Precio)@*</a>*@
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Fecha)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Genero)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Lugar)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Titulo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Precio)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
    <ul class="pagination pagination-lg pager" id="myPager"></ul>
</table>